### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by chrisn-au** [snikch/climate.escea#1]
Just a quick one to say thanks - great addon.

I am running HASSIO in a Debian VM on a mac mini. I did have an initial  error (I did not capture it ) however I believe it was a network permissions error on what i assume was a broadcast to 255.255.255.255 to find fires. 

I have a node.js version which runs on my mac and publishes to mqtt which was working fine. I had a un related power outage which i needed to restart the VM and suddenly all working perfectly.

Thanks again - a lot cleaner than my separate node.js version :-)

**Comment by snikch** [comment]
Hey Chris, thanks for the support. Let me know if you hit that network permissions error again.

Which model fire do you have? I can add it to the list of supported fires.

**Comment by clowg** [comment]
I just wanted to say "Thanks!" too.  The integration is working great with my DX1000.
Are there any other configuration parameters supported in configuration.yaml? 
I would like to name the fire with a friendly name to replace "Escea XXXXX".

**Comment by clowg** [comment]
I found a way to do it in the UI.  Go to Developer Tools/States.  Search for the Entity, and then edit in the 'State attributes' box, and [Set State].

**Comment by snikch** [comment]
Does that persist between restarts?

**Comment by snikch** [comment]
The ideal solution here would be for me to update this component so that it can be edited via the Configuration -> Entities area. It currently can't as I don't think it sets a unique entity id.

![image](https://user-images.githubusercontent.com/115958/84343781-3e636b80-abfd-11ea-803c-af149c47d93e.png)

**Comment by snikch** [comment]
@clowg pull down master and you should be able to update the ui via the Config -> Entities thanks to 3c7f39fa609e429abead845dc3a3c5c09bd4c393.

![image](https://user-images.githubusercontent.com/115958/84345399-5a690c00-ac01-11ea-93f5-25650d68734b.png)

**Comment by clowg** [comment]
> 
> 
> Does that persist between restarts?

Just checking now...

**Comment by clowg** [comment]
> 
> 
> Does that persist between restarts?

Yes it does :-)

**Comment by clowg** [comment]
> @clowg pull down master and you should be able to update the name in the ui via Config -> Entities thanks to [3c7f39f](https://github.com/snikch/climate.escea/commit/3c7f39fa609e429abead845dc3a3c5c09bd4c393).

That worked nicely - thanks :)
