### ISSUE TITLE
"Deprecated" warnings on HA -.110.x

### ISSUE THREAD

**Issue by aheath70** [snikch/climate.escea#2]
Warnings in log about ClimateDevice being deprecated, as per https://developers.home-assistant.io/blog/2020/05/14/entity-class-names/

Needed to change the two instances of ClimateDevice to ClimateEntity. 

Tried to create a pull request, but either I don't have write access to create a branch, or I have no idea what I am doing :(

**Comment by snikch** [comment]
All sorted now by @kendaniels. Thanks for letting me know.
