### ISSUE TITLE
CURRENT_HVAC_IDLE vs CURRENT_HVAC_OFF

### ISSUE THREAD

**Issue by khcnz** [snikch/climate.escea#4]
Hey Snikch,

Is there a particular reason to implement CURRENT_HVAC_IDLE rather than CURRENT_HVAC_OFF when the fireplace is off?

Given you are setting the mode with HVAC_MODE_OFF it would seem to make sense to align to CURRENT_HVAC_OFF? That would also align with other equipment I have.

I've done a PR here https://github.com/khcnz/climate.escea/pull/1/files if you agree I'll test it then do a PR to your branch.

**Comment by snikch** [comment]
Hey, yes please make the PR against my branch. I can't see any reason why I did that, and I definitely can't remember one!

**Comment by SgtBatten** [comment]
As far as I can tell this has been implemented for a while.

**Comment by khcnz** [comment]
Yup it was, thanks @SgtBatten for helping tidyup the rep!
