### ISSUE TITLE
Can't find fire on different subnet

### ISSUE THREAD

**Issue by bjammin** [snikch/climate.escea#9]
My fire is on a different subnet to my home assistant server so it's not able to be autodiscovered by this component.

Is there any way to force it to scan specific subnets, or to manually specify the IP?

**Comment by snikch** [comment]
I don't think you can UDP broadcast to a different subnet, but I could totally be wrong. This would need to be updated in the upstream `escea` package https://github.com/snikch/escea/blob/master/escea/discover.py.

If you wanted to manually specify a fire I don't think that can be done currently, but you could have a look here for adding a fire manually https://github.com/snikch/climate.escea/blob/master/custom_components/escea/climate.py#L27

**Comment by snikch** [comment]
Closing this as I'm not sure there's anything to do here.
